version: '3'

services:
  laravel:
    build: 
      context: laravel/
      dockerfile: prod.Dockerfile
    image: gsluizeduardo/laravel
    container_name: laravel
    networks:
      - laranet
    
  nginx:
    build: 
      context: nginx/
      dockerfile: prod.Dockerfile
    image: gsluizeduardo/nginx
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"
    
networks:
  laranet:
    driver: bridge